services:
  api:
    build:
      context: ../api
      dockerfile: ../api/Dockerfile
      target: development
    command: npm run start:debug
    env_file:
      - ../api/.env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules

  database:
    image: postgres:15-alpine
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres-data:
